### ISSUE TITLE
Failed to download the 'package_sduino_stm8_index.json'

### ISSUE THREAD

**Issue by ArcticLJZ** [tenbaht/sduino#106]
After I type this URL _"https://raw.githubusercontent.com/tenbaht/sduino/master/package_sduino_stm8_index.json"_ into the Additional Board Manager URL(in preferance), it tell me " _Fail to download the json file_"

**Comment by tenbaht** [comment]
Works for me here. Do you still have problems? If yes, which IDE version are you using?
