### ISSUE TITLE
http://sduino.tenbaht.de does not responds

### ISSUE THREAD

**Issue by shridattdudhat** [tenbaht/sduino#108]
The Documentation website is not working.

**Comment by tenbaht** [comment]
Thank you for mentioning this! This is a leftover of a failed DNS experiment. I assumed that I fixed it earlier, but apparently it is still in place. I did another change and will check tomorrow if it works now.
The proper address for the documentation is https://tenbaht.github.io/sduino/

**Comment by shridattdudhat** [comment]
Hello, @tenbaht Thank you for the update.

It is working perfectly. Thank you for your great work on stm8
