### ISSUE TITLE
STM8S

### ISSUE THREAD

**Issue by laxman432** [tenbaht/sduino#109]
HI WE LIKE TO USE STM8SF3P6 OUR APPLICATION WITH GSM COMMUNICATION SO WE LIKE TO USE SOFTWARE SERIAL FOR THAT AND FOR SERIAL CHECKING WE LIKE USE SERIAL PORT  IS MY CONCEPT WORKOUT ? IS IT SUPPORT SOFTSERIAL ?

**Comment by mcer12** [comment]
@laxman432 You might want to check out STM32F030 instead. Slightly more expensive but fully compatible with arduino ide.

**Comment by laxman432** [comment]
ALREADY WE DONE WITH STM32 BLUE PILL BUT WE ARE LOOKING FOR LOW COST CONTROLLER IF ANY SUGGEST ME IT SHOULD SUPPORT ARDUINO PROGRAMING

**Comment by laxman432** [comment]
ALREADY WE DONE WITH STM32 BLUE PILL BUT WE ARE LOOKING FOR LOW COST CONTROLLER IF ANY SUGGEST ME IT SHOULD SUPPORT ARDUINO PROGRAMING

**Comment by mcer12** [comment]
I just suggested you one...

**Comment by tenbaht** [comment]
I am not sure which MCU you mean by STM8SF3P6. But sduino does not support SoftwareSerial (yet). There is HardwareSerial which you could use.
An mcer12 is right: If comprehensive library support is important for your project the STM8 might not be the ideal choice. Have you considered an ATtiny? Full Arduino support, but cheaper than a full ATmega.

**Comment by laxman432** [comment]
Suggest me best in attiny controller like stm8sf3p6  it should support
serial communication only and it should support Arduino ide
