### ISSUE TITLE
add support for Nucleo Boards

### ISSUE THREAD

**Issue by gicking** [tenbaht/sduino#122]
please consider adding support for the Nucleo-8S208RB & STM8S207S8 development board by STM. Thanks a lot in advance!

https://www.st.com/en/evaluation-tools/nucleo-8s208rb.html

https://www.st.com/en/evaluation-tools/nucleo-8s207k8.html

**Comment by mcer12** [comment]
@gicking check this out. At least one of the boards seems to be compatible

**Comment by mcer12** [comment]
https://github.com/stm32duino/Arduino_Core_STM8

**Comment by gicking** [comment]
@mcer12 thanks for pointing this out! However:
- that's a different project (mainly) aiming at STM32
- uses Cosmic compiler and is Windows only

Therefore I would like to keep this issue open

**Comment by mcer12** [comment]
Yes it is, but it’s an option. This repo hasn’t been updated since last year.
