### ISSUE TITLE
Installing issue in Arduino board manager!

### ISSUE THREAD

**Issue by bullygram** [tenbaht/sduino#163]
Team I am unable to install the SDuino, any help will be greatly appreciated!

`Tool sduino:STM8Tools@2019.02.05 already installed
Tool sduino:sdcc@build.11242 already installed
Downloading packages
sduino:stm8@0.5
Installing platform sduino:stm8@0.5
Failed to install platform: sduino:stm8.
Error: 13 INTERNAL: Cannot install platform: installing platform sduino:stm8@0.5: searching package root dir: no unique root dir in archive, found 'C:\Users\MySuerName\AppData\Local\Arduino15\tmp\package-1130421195\STM8S_StdPeriph_Driver' and 'C:\Users\MySuerName\AppData\Local\Arduino15\tmp\package-1130421195\cores'
`
![2024-06-10 17_38_00-sketch_jun10a _ Arduino IDE 2 1 1](https://github.com/tenbaht/sduino/assets/43738997/0f132529-ca28-44ff-9dd2-e7060036c9a4)

**Comment by bullygram** [comment]
Got it fixed, to install the board, use a portable version of Arduino IDE v1.8, and open the latest version of the IDE, the STM8 board is reflected in the board manager. 

We can also use the old IDE but seems to be slow while compiling. but the new IDE is compiling fast!

![2024-06-11 19_32_53-Blink _ Arduino IDE 2 3 2](https://github.com/tenbaht/sduino/assets/43738997/1a5bc461-cadb-4984-b845-89882fe6299b)
![2024-06-11 19_32_02-Window](https://github.com/tenbaht/sduino/assets/43738997/3f3c8df2-f1aa-4b11-ac86-9d5567a16b20)

**Comment by dmikushin** [comment]
I confirm that installing with Arduino IDE 1.8 works, and then usable in Arduino IDE 2.1.1

**Comment by fasax1284** [comment]
I managed to install it on Arduino 2.3.8 by downloading the files from the repo and manually installing them in the Arduino folders.
1. Download Files
Download these two files:
sduino-core-0.5.tar.bz2 (Contains the "core" of the code).
sdcc-stm8-i586-mingw32msvc-20190502-11242.tar.bz2 (Contains the compiler for Windows).

2. Manual Core Installation
Go to the folder: C:\users\....\AppData\Local\Arduino15\packages\

Create a folder called sduino.

Inside sduino, create a folder called hardware, then inside stm8, and finally a folder called 0.5.0.

Open the sduino-core-0.5.tar.bz2 file (use 7-Zip or WinRAR).

Warning: Inside, you'll find several folders such as cores, variants, and libraries. Copy all these folders directly into the 0.5.0 folder you created earlier.

3. Installing the Compiler (SDCC)
Go back to C:\Users\.....\AppData\Local\Arduino15\packages\sduino\.

Create a folder called tools.
Inside tools, create a folder called sdcc.
Inside sdcc, create a folder called build.11242.

Open the sdcc-stm8-i586-mingw32msvc...tar.bz2 file and copy all its contents into the build.11242 folder.

The final structure should look like this:
Plaintext
Arduino15
└── packages
└── sduino
├── hardware
│ └── stm8
│ └── 0.5.0
│ ├── cores
│ ├── libraries
│ └── variants
└── tools
└── sdcc
└── build.11242
└── (compiler files: bin, lib, etc.)
