### ISSUE TITLE
Request: Support for / Opinions on sduino UNO board

### ISSUE THREAD

**Issue by roybaer** [tenbaht/sduino#19]
I spent the last couple of weeks designing this [sduino UNO board](https://github.com/roybaer/sduino_uno) (hope you are okay with me shamelessly borrowing the name).
Now I wanted to ask for opinions on the pin mapping I came up with.

My approach was to try and find as good a function mapping as possible while keeping everything that used to be in a particular AVR port register in one STM8 port register, since this allows for more compatible parallel IO.

It would especially be nice to find a harmonized pin mapping for this STM8S105K6 board and the STM8S105K4 board mentioned in Issue #17 before I get the PCBs manufactured and to hear whether you think that anything about my current pin mapping looks like a silly idea.

EDIT:

I will probably give AREF (i.e. PF4/A12) the pin number 22, change IO14 to pin number 23 and assign pin number 24 to the hardware-SS pin.  I forgot that `pins_arduino.h` reserves pin numbers 14-21 for A0-A7.

Btw.:  I only plan to build about 10 boards myself.  Others can obviously do as they like.

**Comment by tenbaht** [comment]
Whow, that looks amazing! I am looking forward to see the first prototypes!

- I really like the pin mapping. I don't see a way to get closer to the original mapping than this. Used like this, the functional mapping makes sense.
- Implementing the serial interface clearly calls for bootloader support. Somewhere I have read about such a project, but I never looked into it. It would be extremely useful to integrate that here.

Additionally, I wrote some comments regarding the hardware design to your repository.

**Comment by tenbaht** [comment]
integrated by commit 6589a0aa9ec6046e868ed0ee0777637efefa03ba
