### ISSUE TITLE
Suggestion: "Support" forum

### ISSUE THREAD

**Issue by KenjutsuGH** [tenbaht/sduino#20]
Can I suggest that we discuss **sduino** on the the [STM32duino](http://www.stm32duino.com/) forum? Roger Clark already created a STM8 sub-forum: [Home -> Board index -> Bootloaders and Cores -> STM8](http://stm32duino.com/viewforum.php?f=52)

It might just be easier than using github ;-)

**Comment by tenbaht** [comment]
Sounds good to me. This issue tracker is better suited for bug reports and issues tightly related to the repository content. For general discussions and suggestions on Sduino it might be more
convinient to open a thread on the [STM8 board](http://stm32duino.com/viewforum.php?f=52) of the stm32duino forum. It will help to catch my attention to prefix your topic with "[sduino]".

I hope that the need to post a brief self-introduction in the newbie board will not put off too many people.
