### ISSUE TITLE
reference to nonexistant header irqtable.h in Servo library

### ISSUE THREAD

**Issue by evildave666** [tenbaht/sduino#36]
The file sduino/hardware/sduino/stm8/libraries/Servo/src/stm8/Servo.c pulls in irqtable.h, which does not appear to exist.

**Comment by tenbaht** [comment]
Oh, good to know! That include is part of an experiment was not supposed to end up in the master branch, sorry for that.
Just delete the line with in #include statement in sduino/hardware/sduino/stm8/libraries/Servo/src/stm8/Servo.c and it should work fine.
If there is still a problem, please re-open this report!
