### ISSUE TITLE
add a tools entry to unlock a protected MCU

### ISSUE THREAD

**Issue by tenbaht** [tenbaht/sduino#37]
Feature request by gungsukma at http://www.stm32duino.com/viewtopic.php?f=52&t=2682&p=38152#p37635

Please add a menu or something to unlock the protected chip

On linux terminal, it is:
```
echo "00 00 ff 00 ff 00 ff 00 ff 00 ff" | xxd -r -p > factory_defaults.bin
stm8flash -c stlinkv2 -p stm8s103f3 -s opt -w factory_defaults.bin
```

**Comment by all-bear** [comment]
I was getting an error `Tries exceeded` with new `stm8s103f3` chip during upload, but this answer helps me
Upload working now after this command
