### ISSUE TITLE
How to program the chips of stm8s103f?

### ISSUE THREAD

**Issue by thoulin** [tenbaht/sduino#38]
In windows envirement, the sduino core can be merge into Arduino IDE (version of 1.6.8),  I cannot upload the program into chips,can you point out my fault? I have stlink v2 dongle & USB to series tool kit.  I cannot   install the driver for sduino.

**Comment by tenbaht** [comment]
For Windows, you need to install the ST-Link driver from the ST website first.
See https://tenbaht.github.io/sduino/hardware/flashtool/
Hope that helps.

**Comment by thoulin** [comment]
I have installed the STLINK V2 DRIVER，but in arduino envirment, it can not be found. and can you point out more detail of SDCC's installing? and how to link with stlink v2 hardware?

**Comment by tenbaht** [comment]
I am afraid I don't understand what exactly is not working.
Did you do a normal install using the board manager? This will include sdcc, stm8flash and stm8gal, no more manual installations are required.
Could you maybe copy the error message that you get or attach a screenshot from the point where you are stuck?

**Comment by MrAmazoni** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/11248557/38472027-47e39330-3b82-11e8-977e-3913dc7b9757.png)

**Comment by zoomx** [comment]
The STlink drver has also a small utility: STM32 ST-LINK Utility
Check that this utility recognizes the chip. If not there is a communication issue.
Take in account that some STlink clones doesn't work with STM8 but only with STM32. I had one of them.
