### ISSUE TITLE
pinMode() compiles very inefficiently

### ISSUE THREAD

**Issue by tenbaht** [tenbaht/sduino#4]
276 bytes for a simple table lookup and setting a few bits is insane. This might be worth some hand-optimization.

**Comment by ptnicu** [comment]
For STM8S I suggest instead of using LUT to calculate the port register address from pin number.  
pins values should be from 0 to 71.
for data write: 
port_address = GPIO_Base + (pin >> 3) * 5; // 5 registers per port.
pin_bit = 1 << (pin & 0x7);
