### ISSUE TITLE
Installation Instructions...bad link...

### ISSUE THREAD

**Issue by SalvorinFex** [tenbaht/sduino#5]
Howdy, I just tried clicking on your Installation Instructions link:
https://github.com/tenbaht/sduino/blob/master/docs/install.htmk
but it leads to a GitHub 404 page.

I got here via Hackaday, and would like to try this out.

EDIT: Now that I looked at the link I posted, it has HTMK instead of HTML, easy fix  ;)

**Comment by tenbaht** [comment]
On Tue, 21 Feb 2017 13:50:40 -0800
Kurt Roesener <notifications@github.com> wrote:

> Howdy, I just tried clicking on your Installation Instructions link:
> https://github.com/tenbaht/sduino/blob/master/docs/install.htmk
> but it leads to a GitHub 404 page.
> 
> I got here via Hackaday, and would like to try this out.

Thank you for notifing me! I corrected the typo. The real link is:
https://github.com/tenbaht/sduino/blob/master/docs/install.md

It would be great if you could tell me if my description is
understandable or if anything important is missing!

  Michael
