### ISSUE TITLE
Small error in macro in HardwareSerial.h

### ISSUE THREAD

**Issue by lazyan** [tenbaht/sduino#57]
A pitty error was found in the macro Serial_print_sn - there is only one parameter specified and no way to use this function normally. Solution is replace to:

#define Serial_print_sn(S,N)	Print_print_sn(HardwareSerial_write,S,N)

No problem with corresponding println macro.

**Comment by tenbaht** [comment]
Thank you for notifying me!
It took a while to react, but in the next few month I might have more time again for sduino.

**Comment by lazyan** [comment]
Hi,

Thank you for your work you've done for sduino!

Best regards,
Anton Horpynich


пн, 8 окт. 2018 г. в 19:50, Michael Mayer <notifications@github.com>:
