### ISSUE TITLE
Can sduino use sleep mode?

### ISSUE THREAD

**Issue by segatecm** [tenbaht/sduino#63]
I have a project used sduino. I need the STM8S in sleep mode and wake up by GPIO interrupted.
Can I use set_sleep_mode (SLEEP_MODE_PWR_DOWN) or something to do it? 
Thanks.

**Comment by tenbaht** [comment]
Sorry, that is not implement yet. But it would be very useful, so it should go on the list.
Could you maybe post your findings if you manage to get the sleep mode working? I would love to include that into the system.

**Comment by segatecm** [comment]
Hi tenbaht. I am a new hand to stm8.  I want to make some help but I can't. If you make it work I can try it, and thanks for your work.

**Comment by jay-ramani** [comment]
@segatecm, did you find a workaround? Asking since the issue is closed. Not sure if it has been implemented.

**Comment by jay-ramani** [comment]
Ok, I found something - use wfi (wake for interrupt) or halt.

Hope this helps others tripping on the same.

**Comment by chirag-uAtech** [comment]
> Ok, I found something - use wfi (wake for interrupt) or halt.
> 
> Hope this helps others tripping on the same.

I am trying to implement the same. But am unable to find any documentation on this. It would be very helpful if you could share some easy steps for a newbie to implement this.
