### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by gicking** [tenbaht/sduino#7]
hi,
wanted to try sduino, but I am running into problems even with Blinky :-(   Specifically 

- compiler warns repeatedly "type 'double' not supported assuming 'float'". Is there a way to have double support in SDCC? If not, is it possible to somehow replace double globally by float...?

- STM8 Discovery
  - since I do have a STM8SDiscovery board I tried compiling Blinky for that board
  - compiler aborts with many errors like  
`stm8sdisco/pins_arduino.h:370: error 20: Undefined identifier 'TIMER31'`

Here's my setup:
- Ubuntu 16.04
- sdcc fresh install as described in the Wiki

For your support thanks a lot in advance!

**Comment by tenbaht** [comment]
Thank you for filing this problem! It seems to be the same problem as with issue #8  . Could you please confirm if it works now for you? Please reopen if not!

**Comment by gicking** [comment]
hello,
now example "Blinky" compiles and runs for STM8S Discovery :-)
However I still get warnings for double

**Comment by tenbaht** [comment]
Yes, thats a known issue. SDCC doesn't support double. And AFAIK this is not planned for the future.

I was considering adding a `#define double float`. but that might be confusing in case somebody really relies on double precision. You could fix this yourself by adding this line to your Makefile:

```
CPPFLAGS=-Ddouble=float
```

It would be possible to edit the arduino libs as well, but I try to keep the Arduino files as close to the original as possible. Maybe it would be worth giving up on that goal?
