### ISSUE TITLE
digitalWrite doesn't work after analogWrite

### ISSUE THREAD

**Issue by Gei0r** [tenbaht/sduino#72]
I have an issue with `analogWrite()` on the stm8blue board.
A call to `analogWrite()` with 255 should set the pin constantly to `HIGH` (disabling PWM). But that only works sometimes if there was another analog (PWM) value written there before:

    analogWrite(2, 1);
    analogWrite(2, 255);  // pin permanently stays off almost always

    analogWrite(2, 64);
    analogWrite(2, 255);  // works about 25 % of the time, pin stays off otherwise
    
    analogWrite(2, 128);
    analogWrite(2, 255);  // works about 50 % of the time, pin stays off otherwise

    analogWrite(2, 192);
    analogWrite(2, 255);  // works about 75 % of the time, pin stays off otherwise

    analogWrite(2, 254);
    analogWrite(2, 255);  // works almost 100 % of the time

Exchanging the second `analogWrite()` with `digitalWrite()` doesn't make a difference.

It seems that the pin gets "stuck at `LOW`" if the PWM is disabled while the pin is driven low by PWM.

Maybe `turnOffPWM()` in `wiring_digital.c` is insufficient?

    static void turnOffPWM(uint8_t timer)
    {
    	*((unsigned char *) ccmrx[timer-1]) &= ~TIM1_CCMR_OCM;
    }

**Comment by tenbaht** [comment]
Thank you for the report. I will have a look at this after new year's.

**Comment by Gei0r** [comment]
I took a look into the datasheet myself. As I suspected, the code in `turnOffPwm()` only "freezes" the timer comparator, but it does not disable the PWM output driver.

For that, `CCiE` / `CCiNE` in `CCER` need to be cleared. It's fixed in the referenced pull request.

![datasheet](https://user-images.githubusercontent.com/16615274/50547450-fc797c00-0c39-11e9-8bec-1d18ab374d53.png)
