### ISSUE TITLE
Request: board support for stm8s003f3p6 

### ISSUE THREAD

**Issue by aghfars** [tenbaht/sduino#78]
please add support for stm8s003f3p6 on arduino ide

**Comment by mcer12** [comment]
stm8s003f3p6 is already supported, have you tried it?

**Comment by aghfars** [comment]
![image](https://user-images.githubusercontent.com/24976773/64249258-8a73d800-cf28-11e9-8b83-f8f4943216b5.png)
this pic from my board in board manger.
no it isn't here.
where can i found it?

**Comment by mcer12** [comment]
use stm8s103

**Comment by aghfars** [comment]
i need to program stm8s003 not stm8s103
you mean i use stm8s103 to prgram stm8s003 ?

**Comment by mcer12** [comment]
Yes

Dne st 4. 9. 2019 17:18 uživatel aghfars <notifications@github.com> napsal:

**Comment by aghfars** [comment]
yes its worked.
I am not sure but i think it have problem with eeprom because its not same.!!!!!!
and how to set output to push/pull mode?

**Comment by aghfars** [comment]
and i try with stvp and give me that error 
> Reading  PROGRAM MEMORY area...
Error : Cannot communicate with the device !
Check the SWIM cable connection and check all the needed pin connections on the SWIM connector.

If the application code uses Swim Disable and Reset pin as Output or has disabled SWIM Clock Divider:
Try Now to SWITCH OFF and ON the application Power Supply while NRST Reset pin is forced low.

Error : < PROGRAM MEMORY reading failed.

**Comment by aghfars** [comment]
what is the problem?
i double check the wiring. its OK.
how can i fix this?

**Comment by tenbaht** [comment]
The '003 and the '103 are almost identical. The only difference I am aware of is the size of the EEPROM (128 bytes vs. 640 bytes). Just set the board manager for STM8S103 and start compiling. (and don't try to use EEPROM locations > 127 or  > 0x7f).
Since this question keeps popping up I added this to the project website:
https://tenbaht.github.io/sduino/hardware/stm8s003/
