### ISSUE TITLE
PWM issue

### ISSUE THREAD

**Issue by andymsheen** [tenbaht/sduino#9]
Fade example doesn't seem to work.

PWM doesn't seem to work when mixing values analogWrite 1-254 and digitalWrite High and low on the same pin.

**Comment by tenbaht** [comment]
Which pin are you using? Only pins 2,5,6,12 and 13 (PA3, PC3, PC4, PD3, PD4) have full PWM support. The pins 7,8 and 9 (PC5, PC6 and PC7) need to activate the alternative pin function first (not supported yet. Please tell me if you get it working!).
