### ISSUE TITLE
Can I compile for STM8S003F3P6TR? Where to ask questions now that stm32duino is dead?

### ISSUE THREAD

**Issue by ElDominio** [tenbaht/sduino#90]
Title is pretty descriptive. I still lurk around here and everything's kinda dead.

**Comment by tenbaht** [comment]
Yes, you can. The STM8S003 is almost identical to the STM8S003, the only difference is a smaller EEPROM area (and an even lower price). Just compile for any STM8S103 based board (e.g. stm8blue) and make sure not to use more than 128 bytes of EEPROM.

See https://tenbaht.github.io/sduino/hardware/esp14/
