### ISSUE TITLE
PS/2 Library for STM8 board

### ISSUE THREAD

**Issue by tinkerBOY-git** [tenbaht/sduino#91]
First I want to thank the author of this library for STM8 boards! It works great! My only issue is that it won't compile with available PS/2 libraries.

> PS2Keyboard.h:195: syntax error: token -> 'PS2Keyboard' ; column 17

**Comment by tenbaht** [comment]
SDuino is based on plain C, not on C++ as the original Arduino. Since most Arduino libraries are written as a C++ class they need to be modified for use with SDuino first. Often this is not very hard, but this depends on the specific implementation.

**Comment by tinkerBOY-git** [comment]
> SDuino is based on plain C, not on C++ as the original Arduino. Since most Arduino libraries are written as a C++ class they need to be modified for use with SDuino first. Often this is not very hard, but this depends on the specific implementation.

Thank you!
